__include__: [
  '../dataset/voc0712_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/pr_detr_r50vd_base.yml',
]

output_dir: ./output/pr_detr_r50vd_3x_voc0712
max_checkpoint_num: 2

epoches: 36
finetune_epoches: 12

budget_atten: 0.7
budget_mlp: 0.7
budget_conv: 0.7

min_gates_ratio: 0.1

SearchingDistillationLoss:
  attn_w: 0.0001
  mlp_w: 0.0001
  conv_w: 0.0001

SparseRTDETRDecoder:
  spatial_reduce_ratio_list: [8, 8, 6, 4, 2, 1]
  linear_sr_atten: true
  linear_sr_minval: 5

SparseRTDETREncoder:
  spatial_reduce_ratio_list: [6,]
  linear_sr_atten: true
  linear_sr_minval: 5
